version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - .:/app
      - maven-repo:/root/.m2
    develop:
      watch:
        - path: ./pom.xml
          action: rebuild
        - path: ./src
          action: sync

volumes:
  maven-repo:
